name: Build and Conditional Release (.NET Framework 4.8)

on:
  push:
    branches:
      - '**'   # Build on push to any branch
    tags:
      - 'v*'   # Also triggers on version tags

jobs:
  build:
    runs-on: windows-latest
    needs: test
    name: Build AxataLogReader

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore AxataPOS.LogReader.sln

    - name: Build solution
      run: msbuild AxataPOS.LogReader.sln /p:Configuration=Release

    - name: Zip all Release outputs
      run: |
        Compress-Archive -Path (Get-ChildItem -Path . -Recurse -Include *.exe,*.dll | ForEach-Object { $_.FullName }) -DestinationPath AxataLogReader.zip
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: AxataLogReader
        path: AxataLogReader.zip

  release:
    name: Release if Tag on Main
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required to check commit history
        
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: AxataLogReader

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: AxataLogReader.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
