name: .NET Desktop Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2

    - name: Build
      run: |
        msbuild /p:Configuration=Release /m /p:Platform="Any CPU" /t:Rebuild
      working-directory: src

    - name: Deploy
      run: |
      working-directory: src
