name: .NET Desktop Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        msbuild /p:Configuration=Release /m /p:Platform="Any CPU" /t:Rebuild
      working-directory: src

    - name: Deploy
      run: |
        # Add your deployment steps here, such as copying the built binaries to your desired location.
      working-directory: src
